
# Numpy

In [2]:
import numpy as np

## The Basics¶

Quickstart Tutorial - https://docs.scipy.org/doc/numpy-1.13.0/user/quickstart.html#universal-functions

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called *axes*. The number of axes is *rank*.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.

```[[ 1., 0., 0.], 
 [ 0., 1., 2.]]```

NumPy’s array class is called **ndarray** (N-dimensional array). It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

**ndarray.ndim**
>the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

**ndarray.shape**
>the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or number of dimensions, ndim.

**ndarray.size**
>the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**
>an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**
>the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**
>the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

### Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

#### np.array

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [9]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

The type of the array can also be explicitly specified at creation time:

In [7]:
c = np.array([ [1, 2], [3, 4] ], dtype = complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

#### np.zeros, np.ones, np.empty

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

**numpy.zeros**
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.zeros.html#numpy.zeros

Return a new array of given shape and type, filled with zeros.


**Parameters:	**

>**shape** : int or sequence of ints

>> Shape of the new array, e.g., (2, 3) or 2.

>**dtype** : data-type, optional

>>The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

>**order** : {‘C’, ‘F’}, optional

>>Whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory.

**Returns:**	

>**out** : ndarray

>>Array of zeros with the given shape, dtype, and order.


In [12]:
np.zeros( (3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.empty( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

#### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)[source]
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function **linspace** that receives as an argument the number of elements that we want, instead of the step:

In [20]:
np.linspace( 0,2,9 ) # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [23]:
from numpy import pi
x = np.linspace(0, 2*pi, 100) #usefel to evaluate function at lots of points

In [25]:
f = np.sin(x)

### Random Sampling (numpy.random)
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

#### numpy.random.random(size=None)
Return random floats in the half-open interval [0.0, 1.0).

Results are from the “continuous uniform” distribution over the stated interval. To sample Unif[a, b), b > a multiply the output of random_sample by (b-a) and add a:

(b - a) * random_sample() + a
Parameters:	
size : int or tuple of ints, optional
Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

**Parameters: size :** *int or tuple of ints, optional*
>Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

**Returns:	out :** *float or ndarray of floats*
>Array of random floats of shape size (unless size=None, in which case a single float is returned).


In [39]:
np.random.random_sample()

0.7674100090319548

In [40]:
np.random.random_sample((5,))

array([ 0.65942072,  0.94633522,  0.22294062,  0.89772223,  0.10418022])

Three-by-two array of random numbers from [-5, 0):

In [43]:
5 * np.random.random_sample((3, 2)) - 5

array([[-0.83938796, -4.51494644],
       [-1.48153688, -1.26891875],
       [-2.41805796, -4.37260611]])

#### numpy.random.rand(d0, d1, ..., dn)
Random values in a given shape.

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

Parameters:	
d0, d1, ..., dn : int, optional
The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.

In [38]:
np.random.rand(3,2)

array([[ 0.62573532,  0.65700815],
       [ 0.65264368,  0.57843319],
       [ 0.11978195,  0.15053403]])

#### np.random.randn

### Shape Manipulation

#### numpy.arange([start, ]stop, [step, ]dtype=None)
Return evenly spaced values within a given interval.

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

*When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use **linspace** for these cases.*

In [28]:
np.arange(3) #no start (optional), stop, no step (optional), no dtype

array([0, 1, 2])

In [29]:
np.arange(3.0)

array([ 0.,  1.,  2.])

In [30]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [31]:
np.arange(3, 7, 2)

array([3, 5])

#### numpy.reshape(a, newshape, order='C')[source]

In [32]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Printing Arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [34]:
a = np.arange(6) # 1d array
a

array([0, 1, 2, 3, 4, 5])

In [35]:
b = np.arange(12).reshape(4,3) # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
c = np.arange(24).reshape(2,3,4) # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Mathematical functions
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

### Exponents and logarithms

#### np.exp
```(x, /[, out, where, casting, order, ...])```	Calculate the exponential of all elements in the input array.

The irrational number e is also known as Euler’s number. It is approximately 2.718281, and is the base of the natural logarithm, ln 

In [13]:
np.exp(1) # e raised to the power of 1

2.7182818284590451

In [14]:
np.exp(2) # e raised to the power of 2

7.3890560989306504

In [7]:
x = np.linspace(2,8,7)
x

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [8]:
np.exp(x)

array([    7.3890561 ,    20.08553692,    54.59815003,   148.4131591 ,
         403.42879349,  1096.63315843,  2980.95798704])

## Data Type Objects

https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html#arrays-dtypes-constructing

### Specifying and constructing data types

#### Array-scalar types

#### Generic types

#### Built-in Python types

#### Types with .dtype

#### Array-protocol type strings (see The Array Interface) https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.interface.html#arrays-interface

The first character specifies the kind of data and the remaining characters specify the number of bytes per item, except for Unicode, where it is interpreted as the number of characters. The item size must correspond to an existing type, or an error will be raised. The supported kinds are:


- '?'	boolean
- 'b'	(signed) byte
- 'B'	unsigned byte
- 'i'	(signed) integer
- 'u'	unsigned integer
- 'f'	floating-point
- 'c'	complex-floating point
- 'm'	timedelta
- 'M'	datetime
- 'O'	(Python) objects
- 'S', 'a'	zero-terminated bytes (not recommended)
- 'U'	Unicode string
- 'V'	raw data (void)

**Example:**

dt = np.dtype('i4')   # 32-bit signed integer

dt = np.dtype('f8')   # 64-bit floating-point number

dt = np.dtype('c16')  # 128-bit complex floating-point number

dt = np.dtype('a25')  # 25-length zero-terminated bytes

dt = np.dtype('U25')  # 25-character string